---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-issuer
  namespace: cert-manager
secrets:
- name: vault-issuer-token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
