config:
  description: Homer Hive Dashboard
apps:
- name: homer
  repoURL: https://k8s-at-home.com/charts/
  chart: homer
  targetRevision: 8.0.2
  include:
  - ingress-internal
  - noRoot
  - tmpdirs
