config:
  description: Homer Hive Dashboard
apps:
- name: homer
  repoURL: https://helm.samipsolutions.fi
  chart: homer
  targetRevision: 10.0.0
  include:
  - ingress-internal
  - noRoot
  - tmpdirs
