config:
  description: Adguard Home DNS Server

apps:
- name: adguard
  repoURL: https://k8s-at-home.com/charts
  chart: adguard-home
  targetRevision: 5.5.2
    #include:
    #- noRoot
    #- tmpdirs
