config:
  description: Adguard Home DNS Server

apps:
- name: adguard
  repoURL: https://github.com/lib42/charts
  path: charts/adguard-home
  targetRevision: fix/adguard
    #include:
    #- noRoot
    #- tmpdirs
