config:
  description: Public Nextcloud
  networkPolicy:
    groups:
    - internet
    rules:
    - allow-minio

  labels:
    environment: external

apps:
- name: nextcloud
  repoURL: https://nextcloud.github.io/helm
  chart: nextcloud
  targetRevision: 5.0.0
  secrets:
  - name: nextcloud-user
    keys:
    - username
    - password
    - smtp_username
    - smtp_password
  - name: nextcloud-postgres
    keys:
    - postgresql-username
    - postgresql-password
    - postgresql-postgres-password
  - name: bucket
    keys:
    - accesskey
    - secretkey
