config:
  description: Public Nextcloud
  networkPolicy:
    groups:
    - internet
 
  labels:
    environment: external

apps:
- name: nextcloud
  repoURL: https://nextcloud.github.io/helm
  chart: nextcloud
  targetRevision: 2.14.6
  secrets:
  - name: nextcloud-user
    keys:
    - username
    - password
    - smtp_username
    - smtp_password
  - name: nextcloud-postgres
    keys:
    - postgresql-username
    - postgresql-password
    - postgresql-postgres-password
  - name: nextcloud-db
    keys:
    - db-username
    - db-password
