config:
  description: STT & TTS Services

apps:
- name: whisper
  repo: bjw-s 
  chart: app-template
  targetRevision: 1.5.0

- name: piper
  repo: bjw-s 
  chart: app-template
  targetRevision: 1.5.0
