config:
  description: Home Automation
  syncWave: 100
  repo: k8s-at-home
apps:
- name: homeassistant
  chart: home-assistant
  targetRevision: 11.0.5
  secrets:
  - name: hass-postgres
    keys:
    - postgresql-username
    - postgresql-password
    - postgresql-postgres-password
