config:
  description: Home Automation
  syncWave: 100

apps:
- name: homeassistant
  chart: home-assistant
  repoURL: https://charts.pree.dev
  targetRevision: 1.21.1
  secrets:
  - name: bucket
    keys:
    - accesskey
    - secretkey
  - name: influx
    keys:
      - admin-user-password
      - admin-user-token
      - user-password
      - read-user-password
      - write-user-password
  include:
  - ingress-internal

- name: nodered
  chart: node-red
  repoURL: https://schwarzit.github.io/node-red-chart
  targetRevision: 0.23.1
