config:
  description: Home Automation
  syncWave: 100
  repo: k8s-at-home

apps:
- name: homeassistant
  chart: home-assistant
  targetRevision: 11.2.1
  secrets:
  - name: hass-postgres
    keys:
    - postgresql-username
    - postgresql-password
    - postgresql-postgres-password
  - name: bucket
    keys:
    - accesskey
    - secretkey
  include:
  - ingress-internal
