config:
  description: Home Automation
  syncWave: 100

apps:
- name: homeassistant
  chart: home-assistant
  repoURL: https://charts.pree.dev
  targetRevision: 1.21.1
  secrets:
  - name: bucket
    keys:
    - accesskey
    - secretkey
  include:
  - ingress-internal

- name: influx
  chart: influxdb2
  repoURL: https://helm.influxdata.com
  targetRevision: 2.1.1
  secrets:
  - name: influx
    keys:
      - admin-password
      - admin-token

- name: nodered
  chart: node-red
  repoURL: https://schwarzit.github.io/node-red-chart
  targetRevision: 0.23.1
