config:
  description: Home Automation
  syncWave: 100

apps:
- name: homeassistant
  chart: app-template
  repo: bjw-s
  targetRevision: 2.4.0
  secrets:
  - name: bucket
    keys:
    - accesskey
    - secretkey
  include:
  - ingress-internal

- name: influx
  chart: influxdb2
  repoURL: https://helm.influxdata.com
  targetRevision: 2.1.1
  secrets:
  - name: influx
    keys:
      - admin-password
      - admin-token

- name: wmbusmeters
  chart: app-template
  repo: bjw-s
  targetRevision: 2.4.0
