config:
  description: Authentik OIDC

apps:
- name: authentik
  repoURL: https://charts.goauthentik.io/
  chart: authentik
  targetRevision: 2023.10.5
  secrets:
    - name: authentik
      keys:
        - secret_key
    - name: bucket
      keys:
        - secretkey
        - accesskey
    - name: redis
      keys:
        - password
    - name: terraform
      keys:
        - AUTHENTIK_TOKEN
