config:
  description: Bi Agent Framework

apps:
- name: bi
  namespace: bi
  repo: bjw-s
  chart: app-template
  targetRevision: 3.2.1
  secrets:
    - name: bibot
      keys:
        - discord-token
        - ombi-api-key
        - prompt-template
        - instruct-template
        - OPENWEATHERMAP_API_KEY
  ignoreDiff:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

- name: qdrant
  namespace: bi
  repoURL: https://qdrant.github.io/qdrant-helm
  chart: qdrant
  targetRevision: 1.15.2

- name: valkey
  namespace: bi
  repoURL: registry-1.docker.io/bitnamicharts 
  chart: valkey
  targetRevision: 2.2.3

- name: redpanda
  namespace: bi
  repoURL: https://charts.redpanda.com
  chart: redpanda
  targetRevision: 25.1.1
