config:
  description: OpenVoice OS Services

apps:
- name: ovos-tts-server
  repo: bjw-s 
  chart: app-template
  targetRevision: 2.4.0

- name: ovos-stt-server
  repo: bjw-s 
  chart: app-template
  targetRevision: 2.4.0
