config:
  description: Crossplane
  namespace: crossplane-system

apps:
- name: crossplane
  repoURL: https://charts.crossplane.io/stable
  chart: crossplane
  targetRevision: 1.13.2
  secrets:
  - name: s3
    keys:
    - key-file
