config:
  description: Crossplane
  namespace: crossplane-system

apps:
- name: crossplane
  repoURL: https://charts.crossplane.io/stable
  chart: crossplane
  targetRevision: 1.14.4
  secrets:
  - name: terraform
    keys:
    - secret.json
