config:
  description: RomM

apps:
- name: romm
  repo: bjw-s
  chart: app-template
  targetRevision: 5.0.1
  secrets:
    - name: romm
      keys:
        - DB_PASSWD
        - ROMM_AUTH_SECRET_KEY
        - IGDB_CLIENT_ID
        - IGDB_CLIENT_SECRET
        - STEAMGRIDDB_API_KEY
        - SCREENSCRAPER_USER
        - SCREENSCRAPER_PASSWORD

- name: compressatorium
  repo: bjw-s
  chart: app-template
  targetRevision: 5.0.1