podSecurityPolicy:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
  image:
    repository: quay.io/prometheus/node-exporter
    tag: v1.8.2

  hostNetwork: true
  hostPID: true
  hostRootfs: true
  
  extraHostPathMounts:
    - name: textfile-dir
      mountPath: /srv/txt_collector
      hostPath: /var/lib/node-exporter
      readOnly: true
      mountPropagation: HostToContainer
server:
  enabled: true
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.53.2
 
  strategy:
    type: Recreate

  persistentVolume:
    enabled: true

  sidecarContainers:
    smartctl:
      name: smartctl-exporter
      image: matusnovak/prometheus-smartctl:latest
      securityContext:
        runAsNonRoot: false
        privileged: true
      ports:
        - name: metrics
          containerPort: 9902

pushgateway:
  enabled: true

extraScrapeConfigs: |
  - job_name: 'openwrt'
    scrape_interval: 10s
    static_configs:
    - targets: ['192.168.1.1:9100']
  - job_name: 'smartctl'
    scrape_interval: 60s
    static_configs:
     - targets: ['127.0.0.1:9902']
# - job_name: 'octoprint'
#    scrape_interval: 5s
#    metrics_path: '/plugin/prometheus_exporter/metrics'
#    params:
#      apikey: ['__OCTOPRINT_APIKEY__']
#    static_configs:
#      - targets: ['octoprint:80']
