config:
  description: Tools for downloading linux isos
apps:
- name: deluge
  repoURL: https://k8s-at-home.com/charts/
  chart: deluge
  targetRevision: 5.4.2
  secrets:
  - name: openvpn
    keys:
    - VPN_AUTH
    - vpnConfigfile
  include:
  - ingress-internal


- name: youtubedl
  repoURL: https://k8s-at-home.com/charts/
  chart: youtubedl-material
  targetRevision: 4.4.0
  include:
  - ingress-internal

- name: pyload
  repoURL: https://k8s-at-home.com/charts/
  chart: pyload
  targetRevision: 6.4.2
  include:
  - ingress-internal
