config:
  description: Tools for downloading linux isos

apps:
- name: qbittorrent
  #  repoURL: https://lib42.github.io/charts
  repoURL: https://github.com/lib42/charts
  #chart: deluge
  #targetRevision: 1.3.0
  targetRevision: add/qbittorrent
  path: charts/qbittorrent
  secrets:
  - name: wireguard
    keys:
    - WIREGUARD_PRIVATE_KEY
    - SERVER_COUNTRIES

- name: youtubedl
  repo: bjw-s
  chart: app-template
  targetRevision: 4.1.2
