config:
  description: Tools for downloading linux isos

apps:
- name: qbittorrent
  repo: bjw-s
  chart: app-template
  targetRevision: 4.2.0
  secrets:
  - name: wireguard
    keys:
    - SERVER_COUNTRIES
    - WIREGUARD_PRIVATE_KEY
    - WIREGUARD_ENDPOINT_IP 
    - WIREGUARD_PUBLIC_KEY
    - DNS_ADDRESS

- name: youtubedl
  repo: bjw-s
  chart: app-template
  targetRevision: 4.1.2
