---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns-nold
  namespace: core
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:v0.5.1
              envFrom:
                - secretRef:
                    name: cloudflare-ddns-nold
          restartPolicy: OnFailure
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  annotations:
  name: cloudflare-ddns-nold
  namespace: core
spec:
  keys:
  - API_TOKEN
  - NAME
  - RECORD_ID
  - ZONE_ID
  - PROXIED
  path: heqet/core/cloudflare-ddns-nold
  type: Opaque
