---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: nextcloud-bucket-key
  namespace: nextcloud
spec:
  clusterRef:
    name: garage
    namespace: garage
  bucketPermissions:
    - bucketRef: 
        name: nextcloud
        namespace: nextcloud
      read: true
      write: true
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: allow-nextcloud
  namespace: garage
spec:
  from:
    - kind: GarageKey
      namespace: nextcloud
    - kind: GarageBucket
      namespace: nextcloud
  to:
    - kind: GarageCluster
      name: garage
