---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: nextcloud-bucket-key
  namespace: nextcloud
spec:
  clusterRef:
    name: garage
    namespace: garage
  bucketPermissions:
    - bucketRef: 
        name: nextcloud
        namespace: nextcloud
      read: true
      write: true
