apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    recovery:
      source: nextcloud-db

  storage:
    size: 10Gi

  externalClusters:
    - name: nextcloud-db
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage-store
          serverName: nextcloud-db

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: garage-store

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-db-backup
  namespace: nextcloud
spec:
  schedule: "0 0 * * * *"
  backupOwnerReference: self
  cluster:
    name: nextcloud-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
  namespace: nextcloud
spec:
  retentionPolicy: "90d"
  configuration:
    destinationPath: s3://nextcloud/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: nextcloud-bucket-key
        key: access-key-id
      secretAccessKey:
        name: nextcloud-bucket-key
        key: secret-access-key
      region:
        name: nextcloud-bucket-key
        key: region
    wal:
      compression: gzip
