config:
  description: Gitea public Git Server
  networkPolicy:
    groups:
    - internet
    rules:
    - allow-ssh

  labels:
    environment: external

apps:
- name: gitea
  repoURL: https://dl.gitea.io/charts/
  chart: gitea
  targetRevision: 5.0.0
  secrets:
  - name: admin
    keys:
    - username
    - password
    - email
  - name: postgres
    keys:
    - postgresql-password
    - postgresql-postgres-password
