config:
  description: Gitea public Git Server
  networkPolicy:
    groups:
    - internet
    rules:
    - allow-ssh
    - allow-argocd
    - allow-minio

  labels:
    environment: external

apps:
- name: gitea
  repoURL: codeberg.org/forgejo-contrib
  chart: forgejo
  targetRevision: 0.9.2
  secrets:
  - name: admin
    keys:
    - username
    - password
    - email
  - name: bucket
    keys:
    - secretkey
    - accesskey
  - name: redis-auth
    keys:
    - password
