config:
  description: Gitea public Git Server
  networkPolicy:
    groups:
    - internet
    rules:
    - allow-ssh
    - allow-argocd
    - allow-minio

  labels:
    environment: external

apps:
- name: gitea
  repoURL: https://dl.gitea.io/charts/
  chart: gitea
  targetRevision: 7.0.2
  secrets:
  - name: admin
    keys:
    - username
    - password
    - email
  - name: bucket
    keys:
    - secretkey
    - accesskey
