apiVersion: v1
kind: Namespace
metadata:
  name: garage
  labels:
    app.nold.in/name: garage
spec: {}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  finalizers:
  - vaultsecrets.ricoberger.de/finalizer
  generation: 1
  name: admin-token
  namespace: garage
spec:
  keys:
  - admin-token
  path: heqet/garage-operator/admin-token
  type: Opaque
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageCluster
metadata:
  name: garage
  namespace: garage
spec:
  replicas: 1
  zone: us-east-1
  replication:
    factor: 1
  storage:
    data:
      size: 100Gi
  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP
  admin:
    enabled: true
    bindPort: 3903
    adminTokenSecretRef:
      name: admin-token
      key: admin-token
