---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: bi-mongo
  namespace: bi
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: bi
      db: bi
      passwordSecretRef:
        name: bi-mongo-password
      roles:
        - name: dbOwner
          db: bi
      scramCredentialsSecretName: bi
