config:
  desc: Music Streaming
  networkPolicy:
    groups:
    - internet

  labels:
    environment: external

apps:
  - name: navidrome
    repo: bjw-s
    chart: app-template
    targetRevision: 1.5.1
