config:
  description: Argo-Workflows

apps:
- name: argo-workflows
  repoURL: https://argoproj.github.io/argo-helm
  chart: argo-workflows
  targetRevision: 0.41.3
  # secrets:
  # - name: argocd-secret
  #   keys:
  #   - admin.password
  #   - server.secretkey
  #   - dex.authentik.clientSecret
  #   - webhook.gogs.secret
  # - name: ca-cert
  #   keys:
  #   - ca
