config:
  description: S3 Garage Operator

apps:
- name: garage-operator
  repoURL: ghcr.io/rajsinghtech/charts
  chart: garage-operator
  targetRevision: 0.4.6
  parameters:
    - name: watchAnyNamespace
      value: "true"
  secrets:
    - name: admin-token
      keys:
        - admin-token
