---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: forgejo
  namespace: forgejo
spec:
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: forgejo-bucket-key
  namespace: forgejo
spec:
  clusterRef:
    name: garage
    namespace: garage
  bucketPermissions:
    - bucketRef: 
        name: forgejo
        namespace: forgejo
      read: true
      write: true
