apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: garage-store

  bootstrap:
    initdb:
      database: app
      owner: app

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"

  storage:
    size: 10Gi

  externalClusters:
    - name: forgejo
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage-store
          serverName: forgejo
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-db-backup
  namespace: forgejo
spec:
  schedule: "0 0 * * * *"
  backupOwnerReference: self
  cluster:
    name: forgejo-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
  namespace: forgejo
spec:
  retentionPolicy: "90d"
  configuration:
    destinationPath: s3://forgejo/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: forgejo-bucket-key
        key: access-key-id
      secretAccessKey:
        name: forgejo-bucket-key
        key: secret-access-key
      region:
        name: forgejo-bucket-key
        key: region
    wal:
      compression: gzip
