#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository:  sbs20/scanservjs
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [scanservjs documentation](https://scanservjs.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  OCR_LANG: "deu+eng"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: vault-issuer
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: scan.dc
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: scan-tls
      hosts:
      - scan.dc

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  dbus:
    enabled: true
    mountPath: /var/run/dbus
    hostPath: /var/run/dbus
    type: hostPath

  output:
    enabled: true
    mountPath: /app/data/output
    hostPath: /data/paperless/import
    type: hostPath

  config:
    enabled: true
    mountPath: /app/config
    size: 1G
