---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 100Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: homeassistant-bucket-key
  namespace: homeassistant
spec:
  clusterRef:
    name: garage
    namespace: garage
  bucketPermissions:
    - bucketRef: homeassistant
      bucketNamespace: homeassistant
      read: true
      write: true
