apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    recovery:
      source: homeassistant

  backup:
    barmanObjectStore:
      destinationPath: "s3://homeassistant-backup/"
      endpointURL: "http://s3-minio.s3.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: bucket
          key: accesskey
        secretAccessKey:
          name: bucket
          key: secretkey

  storage:
    size: 10Gi

  externalClusters:
    - name: homeassistant
      barmanObjectStore:
        destinationPath: "s3://homeassistant-backup/"
        endpointURL: "http://s3-minio.s3.svc.cluster.local:9000"
        s3Credentials:
          accessKeyId:
            name: bucket
            key: accesskey
          secretAccessKey:
            name: bucket
            key: secretkey
        wal:
          maxParallel: 8

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: homeassistant-db-backup
  namespace: homeassistant
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: homeassistant
