apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    recovery:
      source: homeassistant

  storage:
    size: 10Gi

  externalClusters:
    - name: homeassistant
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage-store
          serverName: homeassistant

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: garage-store


---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: homeassistant-db-backup
  namespace: homeassistant
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: homeassistant
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-store
  namespace: homeassistant
spec:
  retentionPolicy: "90d"
  configuration:
    destinationPath: s3://homeassistant/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: homeassistant-bucket-key
        key: access-key-id
      secretAccessKey:
        name: homeassistant-bucket-key
        key: secret-access-key
      region:
        name: homeassistant-bucket-key
        key: region
    wal:
      compression: gzip
