apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - homeassistant
        source:
          externalCluster: homeassistant

  backup:
    barmanObjectStore:
      destinationPath: "s3://homeassistant-db/"
      endpointURL: "http://minio.minio.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: bucket
          key: accesskey
        secretAccessKey:
          name: bucket
          key: secretkey

  storage:
    size: 10Gi

  externalClusters:
    - name: homeassistant
      connectionParameters:
        host: homeassistant-postgresql.homeassistant.svc.cluster.local
        user: homeassistant
        dbname: nextcloud
      password:
        name: hass-postgres
        key: postgresql-password
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: homeassistant-db-backup
  namespace: homeassistant
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: homeassistant-db
