config:
  description: External Ingress Controller
  networkPolicy:
    config:
      allowNamespace: false
    rules:
    #- allow-dns
    - allow-ingress-traffic
    #- allow-external-services
    #- allow-kubeapi

apps:
- name: ingress-external
  repoURL: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetRevision: 4.8.4
  syncWave: '0'
