config:
  description: External Ingress Controller
  networkPolicy:
    config:
      allowNamespace: false
    rules:
    #- allow-dns
    - allow-ingress-traffic
    #- allow-external-services
    #- allow-kubeapi

apps:
- name: ingress-external
  repoURL: https://helm.traefik.io/traefik
  chart: traefik
  targetRevision: 21.0.0
  syncWave: '0'
