config:
  description: External Ingress Controller
  networkPolicy:
    rules:
    - allow-dns
    - allow-ingress-traffic
    - allow-external-services

apps:
- name: ingress-external
  repoURL: https://helm.traefik.io/traefik
  chart: traefik
  targetRevision: 10.9.1
  syncWave: '0'
