config:
  description: External Ingress Controller
  networkPolicy:
    config:
      allowNamespace: false
    rules:
    - allow-dns
    - allow-proxy
    - allow-ingress-traffic

apps:
- name: ingress-external
  repoURL: https://traefik.github.io/charts
  chart: traefik
  targetRevision: 38.0.1
  syncWave: '0'
