config:
  description: External Ingress Controller
  networkPolicy:
    config:
      allowNamespace: false
    rules:
    #- allow-dns
    - allow-ingress-traffic
    #- allow-external-services
    #- allow-kubeapi

apps:
- name: ingress-external
  repoURL: https://traefik.github.io/charts
  chart: traefik
  targetRevision: 38.0.1
  syncWave: '0'
