config:
  description: LocalAI & LLM Stuff

apps:
- name: localai
  # repoURL: https://go-skynet.github.io/helm-charts
  # chart: local-ai
  # targetRevision: 3.1.0
  repoURL: https://github.com/nold360/localai-charts.git
  path: charts/local-ai
  targetRevision: feat/runtimeclass

- name: anythingllm
  repo: bjw-s 
  chart: app-template
  targetRevision: 2.4.0

- name: flowise
  repo: bjw-s 
  chart: app-template
  targetRevision: 2.4.0
