config:
  description: LocalAI & LLM Stuff

apps:
- name: localai
  # repoURL: https://go-skynet.github.io/helm-charts
  # chart: local-ai
  # targetRevision: 3.1.0
  repoURL: https://github.com/nold360/localai-charts.git
  path: charts/local-ai
  targetRevision: feat/runtimeclass

- name: anythingllm
  repo: bjw-s 
  chart: app-template
  targetRevision: 2.4.0

# - name: flowise
#   repo: bjw-s 
#   chart: app-template
#   targetRevision: 2.4.0

- name: big-agi
  repo: bjw-s
  chart: app-template
  targetRevision: 2.4.0

- name: browserless
  namespace: browserless
  repo: bjw-s
  chart: app-template
  targetRevision: 2.4.0

- name: qdrant
  repoURL: https://qdrant.to/helm
  chart: qdrant
  targetRevision: 0.8.5

- name: bibot
  namespace: bibot
  repo: bjw-s
  chart: app-template
  targetRevision: 2.4.0
  secrets:
    - name: bibot
      keys:
        - discord-token
        - ombi-api-key
        - prompt-template
        - instruct-template
