apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: crossplane-contrib-oci-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  url: xpkg.upbound.io/crossplane-contrib
  type: helm
