apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgres.db.gnu.one
spec:
  claimNames:
    kind: Postgres
    plural: postgres
  defaultCompositeDeletePolicy: Background
  defaultCompositionUpdatePolicy: Automatic
  group: db.gnu.one
  names:
    kind: XPostgres
    plural: xpostgres
  versions:
  - name: v1alpha2
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              name:
                description: Name of the DB to create
                type: string
              storage:
                class:
                  default: '-'
                  description: Storage Class to use for DB
                  type: string
                size:
                  default: 10Gi
                  description: Size of DB Persistent Storage
                  type: string
                type: object
            required:
            - name
            type: object
          status:
            description: A Status represents the observed state
            properties:
              share:
                description: Freeform field containing status information
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
