config:
  description: Forgejo Public Git Server
  networkPolicy:
    groups:
    - internet
    rules:
    - allow-ssh
    - allow-argocd
    - allow-minio

  labels:
    environment: external

apps:
- name: forgejo
  repoURL: codeberg.org/forgejo-contrib
  chart: forgejo
  targetRevision: 3.0.0
  secrets:
  - name: admin
    keys:
    - username
    - password
    - email
  - name: bucket
    keys:
    - secretkey
    - accesskey
  - name: redis-auth
    keys:
      - password

  ignoreDiff:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
