config:
  description: Core Components for Kubernetes

apps:
- name: fast-storage
  namespace: fast-storage
  repoURL: https://github.com/rancher/local-path-provisioner
  path: deploy/chart/local-path-provisioner
  syncWave: '0'
  parameters:
  - name: storageClass.name
    value: fast
  - name: nodePathMap[0].node
    value: DEFAULT_PATH_FOR_NON_LISTED_NODES
  - name: nodePathMap[0].paths[0]
    value: /var/lib/rancher/k3s/storage

- name: ssd-storage
  namespace: ssd-storage
  repoURL: https://github.com/rancher/local-path-provisioner
  path: deploy/chart/local-path-provisioner
  syncWave: '0'
  parameters:
  - name: storageClass.name
    value: ssd
  - name: nodePathMap[0].node
    value: DEFAULT_PATH_FOR_NON_LISTED_NODES
  - name: nodePathMap[0].paths[0]
    value: /data/kubernetes/ssd

- name: metallb
  repoURL: https://metallb.github.io/metallb
  chart: metallb
  namespace: metallb
  targetRevision: 0.13.4
  syncWave: '0'

- name: cert-manager
  namespace: cert-manager
  repoURL: https://charts.jetstack.io
  chart: cert-manager
  targetRevision: v1.9.1
  parameters:
  - name: installCRDs
    value: 'true'
  secrets:
  - name: cert-manager-vault-approle
    keys:
    - secretId

- name: ingress-internal
  namespace: ingress-internal
  repoURL: https://helm.traefik.io/traefik
  chart: traefik
  targetRevision: 10.33.0
  syncWave: '0'

- name: cilium
  existingNamespace: kube-system
  repoURL: https://helm.cilium.io
  chart: cilium
  targetRevision: 1.12.2
