config:
  description: Core Components for Kubernetes

apps:
- name: cert-manager
  namespace: cert-manager
  repoURL: https://charts.jetstack.io
  chart: cert-manager
  targetRevision: v1.7.1
  dependsOn: vault
  parameters:
  - name: installCRDs
    value: 'true'
#  secrets:
#  - name: cert-manager-vault-approle
#    keys:
#    - secretId
