config:
  description: Authentik OIDC

apps:
- name: authentik
  repoURL: https://charts.goauthentik.io/
  chart: authentik
  targetRevision: 2023.3.0
  secrets:
    - name: authentik
      keys:
        - secret_key
    - name: bucket
      keys:
        - secretkey
        - accesskey
