apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: authentik-redis
  namespace: auth
spec:
  sentinel:
    replicas: 1
  redis:
    replicas: 1
  auth:
    secretPath: redis
