config:
  description: Go-Skynet! LocalAI

apps:
  - name: localai
    #repoURL: https://go-skynet.github.io/helm-charts/
    repoURL: https://cowboysysop.github.io/charts/
    chart: local-ai
    targetRevision: 1.6.0
