apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    ---
    use_default_settings:
      engines:
        remove:
          - soundcloud

    server:
      limiter: false
      image_proxy: false

    search:
      default_lang: en
      formats:
        - html
        - json
    #   autocomplete: google

    general:
      instance_name: HiveSearch

    ui:
      static_use_hash: true
      default_theme: simple
      theme_args:
        simple_style: dark
      infinite_scroll: true
      results_on_new_tab: true

    enabled_plugins:
      - Basic Calculator
      - Hash plugin
      - Hostname replace
      - Open Access DOI rewrite
      - Self Informations
      - Tracker URL remover
      - Unit converter plugin

    hostname_replace:
      (www\.)?reddit\.com$: redlib.rostvik.site

  limiter.toml: |
    [real_ip]

    # Number of values to trust for X-Forwarded-For.

    x_for = 1

    # The prefix defines the number of leading bits in an address that are compared
    # to determine whether or not an address is part of a (client) network.

    ipv4_prefix = 32
    ipv6_prefix = 48

    [botdetection.ip_limit]

    # To get unlimited access in a local network, by default link-lokal addresses
    # (networks) are not monitored by the ip_limit
    filter_link_local = true

    # activate link_token method in the ip_limit method
    link_token = false

    [botdetection.ip_lists]

    # In the limiter, the ip_lists method has priority over all other methods -> if
    # an IP is in the pass_ip list, it has unrestricted access and it is also not
    # checked if e.g. the "user agent" suggests a bot (e.g. curl).

    block_ip = [
    ]

    pass_ip = [
      '10.0.0.0/24',      # IPv4 private network
    ]

    # Activate passlist of (hardcoded) IPs from the SearXNG organization,
    # e.g. `check.searx.space`.
    pass_searxng_org = false
