config:
  description: Shared Network Services
apps:
- name: proxy
  namespace: proxy
  repoURL: https://github.com/Nold360/lifen-charts
  path: squid
  targetRevision: f/squid_ingress_fix

- name: minio
  namespace: minio
  repoURL: https://charts.bitnami.com/bitnami
  chart: minio
  targetRevision: 11.3.3
  secrets:
  - name: minio-auth
    keys:
    - root-user
    - root-password

- name: mqtt
  chart: mosquitto
  repo: k8s-at-home
  targetRevision: 4.3.1
