config:
  description: Shared Network Services
apps:
- name: proxy
  namespace: proxy
  repoURL: https://lib42.github.io/charts
  chart: squid
  targetRevision: 1.1.0

- name: minio
  namespace: minio
  repoURL: https://charts.bitnami.com/bitnami
  chart: minio
  targetRevision: 12.1.7
  secrets:
  - name: minio-auth
    keys:
    - root-user
    - root-password

- name: cnpg
  namespace: cnpg-system
  repoURL: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  targetRevision: 0.17.0
