config:
  description: Shared Network Services
apps:
- name: proxy
  namespace: proxy
  repoURL: http://honestica.github.io/lifen-charts
  chart: squid
  targetRevision: 0.4.1
- name: minio
  namespace: minio
  repoURL: https://charts.bitnami.com/bitnami
  chart: minio
  targetRevision: 10.1.4
  secrets:
  - name: minio-auth
    keys:
    - root-user
    - root-password
