config:
  description: Shared Network Services
apps:
- name: proxy
  namespace: proxy
  repoURL: https://lib42.github.io/charts
  chart: squid
  targetRevision: 1.3.0

- name: s3
  namespace: s3
  repoURL: https://charts.min.io
  chart: minio
  targetRevision: 5.4.0
  secrets:
  - name: minio-root
    keys:
    - rootUser
    - rootPassword

- name: cnpg
  namespace: cnpg-system
  repoURL: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  targetRevision: 0.26.0

- name: redis-operator
  repoURL: https://ot-container-kit.github.io/helm-charts
  namespace: redis-operator
  chart: redis-operator
  targetRevision: 0.16.4
