config:
  description: Crowdsec

apps:
- name: crowdsec
  repoURL: https://crowdsecurity.github.io/helm-charts
  chart: crowdsec
  targetRevision: 0.22.0
  secrets:
    - name: crowdsec
      keys:
        - BOUNCER_KEY_TRAEFIK

- name: crowdsec-webui
  repo: bjw-s
  chart: app-template
  targetRevision: 4.6.0
  secrets:
  - name: crowdsec-webui
    keys:
    - CROWDSEC_PASSWORD