config:
  description: Drone-CI

  networkPolicy:
    groups:
    - internet
    rules:
    - allow-runner
    - allow-minio

  labels:
    environment: external

apps:
  - name: drone
    repoURL: https://charts.drone.io
    chart: drone
    targetRevision: 0.6.4
    secrets:
      - name: drone-env
        keys:
          - DRONE_GITEA_SERVER
          - DRONE_GITEA_CLIENT_ID
          - DRONE_GITEA_CLIENT_SECRET
          - DRONE_GITHUB_CLIENT_ID
          - DRONE_GITHUB_CLIENT_SECRET
          - DRONE_RPC_SECRET
          - DRONE_GIT_USERNAME
          - DRONE_GIT_PASSWORD

  - name: drone-runner
    namespace: drone-runner
    repoURL: https://charts.drone.io
    chart: drone-runner-kube
    targetRevision: 0.1.10
    secrets:
      - name: drone-env
        fromApp: drone
        keys:
        - DRONE_RPC_SECRET
        - DRONE_SECRET_PLUGIN_TOKEN
