config:
  description: ArgoCD - Continous Deployment from Git
apps:
- name: argocd
  namespace: argo
  repoURL: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetRevision: 3.35.4
  syncWave: '0'
  secrets:
  - name: argocd-secret
    keys:
    - admin.password
    - server.secretkey
    - oidc.auth0.clientSecret
  - name: ca-cert
    keys:
    - ca
