{
 "title": "~| The Hive |~",
 "description": "Metrics for Single Host K3s Homelab",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info, server)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "Filters" },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alertmanager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  {
   "title": "The Hive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage rate（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{container=\"node-exporter\"} - node_memory_MemFree_bytes{container=\"node-exporter\"}) / (node_memory_MemTotal_bytes{container=\"node-exporter\"}))* 100"
    }
   ]
  },
  {
   "title": "Root partition usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\",container=\"node-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype=~\"ext4|xfs\",container=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\",sync_status!=\"Unknown\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{node=\"hive\", service=\"kubelet\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job!=\"node-exporter\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of DNS queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_num_dns_queries{}" }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=\"127.0.0.1\"} / adguard_num_dns_queries{hostname=\"127.0.0.1\"} * 100"
    }
   ]
  },
  {
   "title": "System average load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Top clients by source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_top_clients", "legendFormat": "{{ client }}" }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, adguard_top_blocked_domains{})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by(container) (increase(kube_pod_container_status_restarts_total[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.1.111:9100\"} - (node_memory_MemFree_bytes{instance=\"192.168.1.111:9100\"}  + node_memory_Buffers_bytes{instance=\"192.168.1.111:9100\"}  + node_memory_Cached_bytes{instance=\"192.168.1.111:9100\"} )",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.1.111:9100\"} ",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"192.168.1.111:9100\"} ",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.1.111:9100\"} ",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "io wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " irate(node_intr_total[5m])", "legendFormat": "interrupts" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin[1m]) * 4096 or irate(node_vmstat_pswpin[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout[1m]) * 4096 or irate(node_vmstat_pswpout[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (device)(node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs\",mountpoint!~\"/export.*\"})"
    },
    {
     "expr": "sum by (device) (node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs\",mountpoint!~\"/export.*\"})"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs\",mountpoint!~\"/export.*\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs|zfs\",mountpoint!~\"/export.*\"})"
    }
   ]
  },
  {
   "title": "ZPOOL - Ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_reads{instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "irate(node_zfs_zpool_writes{instance=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  },
  {
   "title": "ARC - Hit %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_data_misses{instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{instance=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{instance=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{instance=~\"$node\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"192.168.1.111:9100\",device=~\"$diskdevices\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",device=~\"$diskdevices\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cilium Forwarded Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(cilium_forward_bytes_total[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Cilium Dropped Package Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 72 },
   "targets": [
    {
     "expr": "rate(cilium_drop_count_total[5m])",
     "legendFormat": "{{ direction }}: {{reason}}"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{image!=\"\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod}}"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{name!=\"\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{name!=\"\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bps", "label": "upload（-）/download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out upload"
    }
   ]
  },
  {
   "title": "Ingress - Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_size_sum[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "External Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_namespace=\"ingress-external\", status!~\"[4-5].*\"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_namespace=\"ingress-external\"}[5m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\"}[5m] ) )",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "graph",
   "description": "CurrEstab - number of TCP connections with current state of ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from the CLOSED state to the SYN-SENT state (within 1 minute)\n\nPassiveOpens - TCP average connections that have been converted from the LISTEN state to the SYN-RCVD state (within 1 minute)\n\nTCP_alloc - the number of TCP sockets that have been allocated (established, applied to sk_buff)\n\nTCP_inuse - the number of TCP sockets being used (listening)\n\nTCP_tw - number of TCP connections waiting to be closed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\"}) by (container_name, image))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{image!=\"\"}[5m]) ",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "OpenWRT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OpenWRT - Network Traffic by Bytes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "deckbytes", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.1.1:9100\",job=~\"openwrt-router\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.1.1:9100\",job=~\"openwrt\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Wifi Bridge - Network Traffic by Bytes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "deckbytes", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.1.2:9100\",job=~\"openwrt-bridge\"}[5m])/1024",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.1.1:9100\",job=~\"openwrt\"}[5m])/1024",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  }
 ]
}