config:
  description: Arrr I'm a pirate!
  syncWave: 100
  repo: k8s-at-home

apps:
- name: ombi
  namespace: ombi
  chart: ombi
  targetRevision: 11.1.0
  include:
  - ingress-internal

- name: prowlarr
  chart: prowlarr
  namespace: prowlarr
  repoURL: https://charts.pree.dev
  targetRevision: 1.4.0
  include:
  - ingress-internal

- name: flaresolverr
  chart: flaresolverr
  namespace: flaresolverr
  repo: lib42
  targetRevision: 1.0.0
  include:
  - ingress-internal

- name: sonarr
  namespace: sonarr
  chart: sonarr
  targetRevision: 15.2.1
  include:
  - noRoot
  - tmpdirs
  - ingress-internal

- name: radarr
  namespace: radarr
  chart: radarr
  targetRevision: 15.1.1
  include:
  - noRoot
  - tmpdirs
  - ingress-internal

- name: lidarr
  namespace: lidarr
  chart: lidarr
  targetRevision: 13.1.1
  include:
  - noRoot
  - tmpdirs
  - ingress-internal

- name: bazarr
  chart: bazarr
  targetRevision: 10.2.0
  include:
  - noRoot
  - tmpdirs
  - ingress-internal

- name: unpackerr
  chart: unpackerr
  targetRevision: 5.1.0
  include:
  - noRoot
  - tmpdirs
  - ingress-internal
  secrets:
    - name: unpackerr-config
      keys:
        - UN_LIDARR_0_API_KEY
        - UN_RADARR_0_API_KEY
        - UN_SONARR_0_API_KEY
