apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-only
  namespace: ingress-external
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          environment: external

