config:
  description: Woodpecker-CI
  repoURL: https://woodpecker-ci.org
  targetRevision: v0.15.5

  networkPolicy:
    groups:
    - internet

  labels:
    environment: external


apps:
  - name: woodpecker-server
    chart: woodpecker-server
    secrets:
      - name: github-oauth
        keys:
        - WOODPECKER_GITHUB_CLIENT
        - WOODPECKER_GITHUB_SECRET
      - name: woodpecker-secret
        keys:
          - WOODPECKER_AGENT_SECRET

  - name: woodpecker-agent
    namespace: woodpecker-agent
    chart: woodpecker-agent
    secrets:
      - name: woodpecker-secret
        fromApp: woodpecker-server
        keys:
        - WOODPECKER_AGENT_SECRET
