config:
  description: Woodpecker-CI
  repoURL: https://github.com/woodpecker-ci/helm
  targetRevision: main

  networkPolicy:
    groups:
    - internet

  labels:
    environment: external


apps:
  - name: woodpecker-server
    path: charts/server
    secrets:
      - name: github-oauth
        keys:
        - WOODPECKER_GITHUB_CLIENT
        - WOODPECKER_GITHUB_SECRET
      - name: woodpecker-secret
        keys:
          - WOODPECKER_AGENT_SECRET

  - name: woodpecker-agent
    namespace: woodpecker-agent
    path: charts/agent
    secrets:
      - name: woodpecker-secret
        fromApp: woodpecker-server
        keys:
          - WOODPECKER_AGENT_SECRET
