config:
  description: Authentik Authentication

apps:
  - name: authentik
    repoURL: https://charts.goauthentik.io/
    chart: authentik
    targetRevision: 4.0.3
    secrets:
      - name: authentik
        keys:
        - secret_key
      - name: postgres
        keys:
          - postgresql-username
          - postgresql-password
          - postgresql-postgres-password
      - name: redis
        keys:
          - password
